language: python
python:
    - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  pytest --cov=app tests/ --cov-report xml

after_success:
  - coveralls
