"""empty message

Revision ID: 7eb260563216
Revises: 0323c719701d
Create Date: 2017-01-18 08:45:04.792506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb260563216'
down_revision = '0323c719701d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
